version: '4'
services:
  manage-warehouse:
    image: manage-warehouse:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    networks:
      - my-network

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 228488432
      POSTGRES_DB: manageWarehouse
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my-network

volumes:
  pgdata:

networks:
  my-network:
